apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist
  labels:
    app: wishlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
        - name: nginx
          image: ddanielgal/wishlist
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: wishlist
  labels:
    app: wishlist
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: wishlist
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wishlist
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - danielgal.eu
      secretName: wishlist-danielgal-ingress-tls
  rules:
    - host: danielgal.eu
      http:
        paths:
          - path: /kivansaglista
            pathType: Prefix
            backend:
              service:
                name: wishlist
                port:
                  number: 80
